# Generated by Django 4.2.6 on 2023-11-02 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
