# Generated by Django 4.2.6 on 2023-11-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0004_alter_customuser_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalFacility',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('img', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
